name: NodeJS CI/CD
description: Github workflow to execute ci as part of a github workflow for NodeJS projects
on:
  workflow_call:
    inputs:
      code-analysis:
        required: false
        type: string
      publish:
        required: false
        type: string
      deploy:
        required: false
        type: string
      node-version:
        required: false
        type: string
        default: '22.x'
    secrets:
      snyk-token:
        required: false
      npm-token:
        required: false
    outputs:
      github_pages_url:
        value: ${{ jobs.deploy.outputs.github_pages_url }}
jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk Test
        uses: tarsilla-app/actions/code-analysis/node@main
        with:
          config: ${{ inputs.code-analysis }}
          snyk-token: ${{ secrets.snyk-token }}
          node-version: ${{ inputs.node-version }}
  publish:
    runs-on: ubuntu-latest
    needs: [code-analysis]
    steps:
      - name: Publish Library
        uses: tarsilla-app/actions/publish/node@main
        with:
          config: ${{ inputs.publish }}
          npm-token: ${{ secrets.npm-token }}
          node-version: ${{ inputs.node-version }}
  deploy:
    runs-on: ubuntu-latest
    needs: [code-analysis]
    outputs:
      github_pages_url: ${{ steps.deploy.outputs.github_pages_url }}
    steps:
      - id: deploy
        name: Deploy Site
        uses: tarsilla-app/actions/deploy/node@main
        with:
          config: ${{ inputs.deploy }}
          node-version: ${{ inputs.node-version }}